// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYPvebsgoCQDnnps3EUv8qtg16st7a-kQ',
    appId: '1:374820919742:web:9c34438d502f74cb4ac1ef',
    messagingSenderId: '374820919742',
    projectId: 'ash-79th-306',
    authDomain: 'ash-79th-306.firebaseapp.com',
    storageBucket: 'ash-79th-306.firebasestorage.app',
    measurementId: 'G-HPWQ24BGCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA6KjArdz1p7EvBvJadNWbrsA4x9lHQIQ',
    appId: '1:374820919742:android:6c6e1aaad1aaf1034ac1ef',
    messagingSenderId: '374820919742',
    projectId: 'ash-79th-306',
    storageBucket: 'ash-79th-306.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrftBrArfk_5KnIll-XDlFXQBPllMREhQ',
    appId: '1:374820919742:ios:02e4b415ee3223e44ac1ef',
    messagingSenderId: '374820919742',
    projectId: 'ash-79th-306',
    storageBucket: 'ash-79th-306.firebasestorage.app',
    iosBundleId: 'com.example.asahi79th306',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrftBrArfk_5KnIll-XDlFXQBPllMREhQ',
    appId: '1:374820919742:ios:02e4b415ee3223e44ac1ef',
    messagingSenderId: '374820919742',
    projectId: 'ash-79th-306',
    storageBucket: 'ash-79th-306.firebasestorage.app',
    iosBundleId: 'com.example.asahi79th306',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYPvebsgoCQDnnps3EUv8qtg16st7a-kQ',
    appId: '1:374820919742:web:c493f7c4a85481464ac1ef',
    messagingSenderId: '374820919742',
    projectId: 'ash-79th-306',
    authDomain: 'ash-79th-306.firebaseapp.com',
    storageBucket: 'ash-79th-306.firebasestorage.app',
    measurementId: 'G-JY7WE7EBPT',
  );
}
